name: Sync dependencies
on: [workflow_dispatch, push]

jobs:
    run:
        name: Sync dependencies
        runs-on: ubuntu-20.04

        steps:
            - name: Checkout
              uses: actions/checkout@v3.1.0
              with:
                  ref: ${{ github.head_ref }}

            - name: Bump dependnencies
              uses: RedGuy12/sync-types@v0.0.2

            - name: Commit
              uses: stefanzweifel/git-auto-commit-action@v4.15.4
              with:
                  commit_message: Update dependencies
                  branch: ${{ github.head_ref }}
