name: Deploy bot
on:
    workflow_dispatch:
    release:
        types: [published]

jobs:
    run:
        name: Deploy bot
        runs-on: ubuntu-20.04

        steps:
            - name: Checkout
              uses: actions/checkout@v3.0.2
              with:
                  ref: "v1.9.4"#${{ github.head_ref }}

            - name: Deploy
              uses: akhileshns/heroku-deploy@v3.12.12
              with:
                   heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
                   heroku_app_name: "scradd"
                   heroku_email: "paul@reid-family.org"
                   branch: "v1.9.4"
                   usedocker: true
                   docker_heroku_process_type: worker
#                    procfile: "worker: npm start"
