name: Lint
on: [push, pull_request_target, workflow_dispatch]

jobs:
    setup:
        name: Setup
        runs-on: ubuntu-20.04

        steps:
            - name: Checkout
              uses: actions/checkout@v3.1.0
              with:
                  ref: ${{ github.head_ref }}

            - name: Setup Node.JS
              uses: actions/setup-node@v3.5.1
              with:
                  node-version: "18.12.1"
                  cache: "npm"

    bump:
        name: Bump dependencies
        needs: [setup]
        runs-on: ubuntu-20.04

        steps:
            - name: Bump dependnencies
              uses: RedGuy12/sync-types@v1.0.2

            - name: Commit
              uses: stefanzweifel/git-auto-commit-action@v4.15.4
              with:
                  commit_message: Bump dependencies
                  branch: ${{ github.head_ref }}

            - name: Install
              run: npm ci

    format:
        name: Format
        if: ${{ steps.setup.outcome }} == 'success'
        needs: [bump]
        runs-on: ubuntu-20.04

        steps:
            - name: Format
              run: npm run format

            - name: Commit
              uses: stefanzweifel/git-auto-commit-action@v4.15.4
              with:
                  commit_message: Format
                  branch: ${{ github.head_ref }}

    build:
        name: Build
        if: ${{ steps.setup.outcome }} == 'success'
        needs: [bump]
        runs-on: ubuntu-20.04

        steps:
            - name: Build
              run: npm build
